apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express-andreas-namespace
  namespace: johauand 
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-express-andreas-namespace
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/AndreasJohansson1990/test-own-namespace.git
    subPath: node-express-andreas-namespace
